name: cairo_metro_guide
description: Beginner-friendly Cairo Metro team architecture starter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: 12.0.0
  http: 1.6.0
  shared_preferences: 2.3.2
  url_launcher: 6.3.2

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
